### ISSUE TITLE
May be having a pathing issue

### ISSUE THREAD

**Issue by JoeDuncko** [TeamImpatientBanana/flat#16]
Check out the locations of these files in the last commit @Jarvl 
![screenshot 2](https://cloud.githubusercontent.com/assets/6749768/5812611/5d70955c-a03c-11e4-932a-398ed991e171.png)

**Comment by Jarvl** [comment]
I need to put in some logic that will keep all the files accessible while I rename them. Working on this now.

**Comment by Jarvl** [comment]
I'm halfway through this one. One of the issues I saw was that the file was being read from its static path on the server rather than from a relative path. This would be an issue if we happened to migrate servers.

Also, I added logic to support bad file names/paths while still uploading files into the correct location and reading from that location as well. It gives us the ability to rename and move the bad files at our convenience without breaking links (Also another reason why the id parameter was implemented; I can be more flexible on the back-end).

**Comment by Jarvl** [comment]
Had some down time, but its fixed
